name: CI - Build Docker Images

on:
  push:
    paths:
      - task-service/**
      - user-service/**
    branches: [ main ]
  pull_request:
    paths:
      - task-service/**
      - user-service/**
    branches: [ main ]

jobs:
  user-service-build-and-push:
    name: user-service Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image with tag
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/user-service
          TAG=$(echo $GITHUB_SHA | cut -c1-7)
          docker build -t $IMAGE:$TAG -t $IMAGE:latest ./user-service
          docker push $IMAGE:$TAG
          docker push $IMAGE:latest

  task-service-build-and-push:
    name: task-service Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image with tag
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/task-service
          TAG=$(echo $GITHUB_SHA | cut -c1-7)
          docker build -t $IMAGE:$TAG -t $IMAGE:latest ./task-service
          docker push $IMAGE:$TAG
          docker push $IMAGE:latest

